# https://github.com/bitwarden/clients/blob/main/.github/workflows/build-browser.yml
---
name: Build

on:
  workflow_dispatch:
  push:
    branches: [master, main]

permissions: write-all

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18 # See .nvmrc

      - name: Setup repo
        run: |
          chmod +x setup_repo.sh
          ./setup_repo.sh

      - name: Print environment
        run: |
          node --version
          npm --version

      - name: Apply patch
        run: |
          chmod +x patch_code.sh
          ./patch_code.sh

      - name: Build
        run: |
          chmod +x build_extension.sh
          ./build_extension.sh

      - name: Upload Chrome artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          path: clients/apps/browser/dist/dist-chrome.zip
          name: dist-chrome

      - name: Upload Edge artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          path: clients/apps/browser/dist/dist-edge.zip
          name: dist-edge

      - name: Upload dist folder
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          path: clients/apps/browser/dist/
          name: dist

      - uses: marvinpinto/action-automatic-releases@d68defdd11f9dcc7f52f35c1b7c236ee7513bcc1 # Last commit before archived
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest Workflow Output"
          files: |
            clients/apps/browser/dist/*
